# re-export all modules

from .basemodule import BaseModule  # isort: skip

from ._autogenerated_activationfuncs import *  # noqa: F403
from .affineeigenvaluepmm import AffineEigenvaluePMM
from .affinehermitianmatrix import AffineHermitianMatrix
from .affineobservablepmm import AffineObservablePMM
from .bias import Bias
from .comment import Comment
from .concatenateleaves import ConcatenateLeaves
from .constant import Constant
from .eigensystem import Eigensystem
from .eigenvalues import Eigenvalues
from .eigenvectors import Eigenvectors
from .einsum import Einsum
from .expectationvaluesum import ExpectationValueSum
from .flatten import Flatten
from .funcbase import FuncBase

# from .func import Func
# from .legacyaffineobservablepmm import LegacyAffineObservablePMM
from .linearnn import LinearNN
from .matmul import MatMul

# from .lowrankaffineeigenvaluepmm import LowRankAffineEigenvaluePMM
# from .lowrankaffinehermitianmatrix import LowRankAffineHermitianMatrix
# from .lowrankaffineobservablepmm import LowRankAffineObservablePMM
# from .lowranktransitionamplitudesum import LowRankTransitionAmplitudeSum
from .prelu import PReLU
from .reshape import Reshape
from .transitionamplitudesum import TransitionAmplitudeSum
from .treeflatten import TreeFlatten
from .treekey import TreeKey

# aliases for shortcuts
AEPMM = AffineEigenvaluePMM
AOPMM = AffineObservablePMM
# LRAEPMM = LowRankAffineEigenvaluePMM
# LRAOPMM = LowRankAffineObservablePMM


__all__ = [  # noqa: F405
    "AEPMM",
    "AOPMM",
    "Bias",
    # "LRAEPMM",
    # "LRAOPMM",
    "AffineEigenvaluePMM",
    "AffineHermitianMatrix",
    "AffineObservablePMM",
    "BaseModule",
    "Comment",
    "ConcatenateLeaves",
    "Constant",
    "Eigenvalues",
    "Eigenvectors",
    "Eigensystem",
    "Einsum",
    "ExpectationValueSum",
    "Flatten",
    "FuncBase",
    # "LegacyAffineObservablePMM",
    "LinearNN",
    "MatMul",
    "PReLU",
    "Reshape",
    "TreeFlatten",
    "TreeKey",
    # "LowRankAffineHermitianMatrix",
    # "LowRankAffineEigenvaluePMM",
    "TransitionAmplitudeSum",
    # "LowRankTransitionAmplitudeSum",
    # "LowRankAffineObservablePMM",
    # autogenerated activation functions
    "ReLU",
    "ReLU6",
    "Sigmoid",
    "Softplus",
    "SparsePlus",
    "SparseSigmoid",
    "SoftSign",
    "SiLU",
    "Swish",
    "LogSigmoid",
    "LeakyReLU",
    "HardSigmoid",
    "HardSiLU",
    "HardSwish",
    "HardTanh",
    "ELU",
    "CELU",
    "SELU",
    "GELU",
    "GLU",
    "SquarePlus",
    "Mish",
    "Identity",
    "Softmax",
    "LogSoftmax",
    "LogSumExp",
    "Standardize",
    "OneHot",
    # Elementwise numpy functions
    "Abs",
    "Absolute",
    "ACos",
    "ACosh",
    "AMax",
    "AMin",
    "Angle",
    "ArcCos",
    "ArcCosh",
    "ArcSin",
    "ArcSinh",
    "ArcTan",
    "ArcTan2",
    "ArcTanh",
    "ASin",
    "ASinh",
    "ATan",
    "ATanh",
    "Cbrt",
    "Ceil",
    "Clip",
    "Conj",
    "Conjugate",
    "Cos",
    "Cosh",
    "Deg2Rad",
    "Degrees",
    "Exp",
    "Exp2",
    "Expm1",
    "FAbs",
    "Fix",
    "FloatPower",
    "Floor",
    "FloorDivide",
    "FrExp",
    "I0",
    "Imag",
    "Invert",
    "LDExp",
    "Log",
    "Log10",
    "Log1p",
    "Log2",
    "NaNToNum",
    "NanToNum",
    "NextAfter",
    "Packbits",
    "Piecewise",
    "Positive",
    "Pow",
    "Power",
    "Rad2Deg",
    "Radians",
    "Real",
    "Reciprocal",
    "RInt",
    "Round",
    "Sign",
    "Signbit",
    "Sin",
    "Sinc",
    "Sinh",
    "Sqrt",
    "Square",
    "Tan",
    "Tanh",
    "Trunc",
    "Unpackbits",
]
